# ------------------------------------------------------------------------------
---
name: accessibility
on:
  workflow_dispatch:

jobs:
  pa11y:
    runs-on: ubuntu-latest
    steps:
    -
      name: Checkout code
      uses: actions/checkout@v3
    -
      name: Run pa11y
      run: |
        npm install pa11y
        node ./interimSite.js
